{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-protein-pca
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - maturin ==0.10.0
    - rust ==1.51.0

  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-alignment {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_protein_pca
    - qiime2.plugins.protein_pca
    - aln_ranking
  commands:
    - pytest --cov q2_protein_pca --pyargs q2_protein_pca

about:
  home: https://github.com/bokulich-lab/q2-protein-pca
  license: BSD-3-Clause
  license_family: BSD
