name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: python -m pip install --upgrade pip
      - name: lint
        run: |
          pip install -q https://github.com/qiime2/q2lint/archive/master.zip
          q2lint
          pip install -q flake8
          flake8

  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
        working-directory: ./ranking

  build-and-test:
    needs: [lint, rust-test]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # necessary for versioneer
          fetch-depth: 0
      # TODO: update this to @v1 when it lands
      - uses: qiime2/action-library-packaging@alpha1
        with:
          package-name: q2-protein-pca
          additional-tests: pytest --pyargs q2_protein_pca
          # TODO: update this to `released` when tagging release
          build-target: staged
          library-token: ${{ secrets.LIBRARY_TOKEN }}
