name: test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up conda
        uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.6
          channels: conda-forge,bioconda,qiime2,defaults
          channel-priority: true
          add-pip-as-python-dependency: true
          activate-environment: qiime2-protein
      - name: run tests with coverage
        shell: bash -l {0}
        run: |
          conda install -y -q qiime2 q2cli q2templates q2-types q2-alignment pytest-cov "pandas=>0.25.3"
          pip install https://github.com/misialq/q2-types/archive/protein-seqs.zip
          pip install .
          qiime dev refresh-cache
          pytest --cov=q2_protein_pca
